<?php
namespace app\modules\todo;

use yii\console\Application;

class Module extends \yii\base\Module
{

    public $controllerNamespace = 'app\modules\todo\controllers';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if( \Yii::$app instanceof Application) {
            $this->controllerNamespace = 'app\modules\todo\commands';
        }

    }

}